softeerbootcamp-6th/Team6-6CanDoIt

- backend/src/main/resources/application.properties
- backend/src/main/resources/application.yml
applcation 확장자 properties -> yml 이름 변경
close #
> 💎 Refactor: properties -> yml 이름 변경

- frontend/src/components/atoms/Icon/Icons.tsx
Icon svg 의 width와 height를 viewBox와 연동하여 안정적이게 보일 수 있도록 변경
width와 height를 rem단위로 숫자로 받은 후 viewbox는 이를 통해 계산하여 크기를 결정해준다.
> 🎨 - Icon viewBox width와 height연동

- backend/application-modules/api-server/build.gradle
- backend/application-modules/api-server/src/test/resources/application.yml
- backend/application-modules/batch-server/build.gradle
- backend/application-modules/batch-server/src/test/resources/application.yml
- backend/application-modules/build.gradle
- backend/build.gradle
- backend/domain-modules/build.gradle
- backend/domain-modules/image-domain/build.gradle
- backend/domain-modules/image-domain/src/test/resources/application.yml
- backend/settings.gradle
모듈 별 테스트를 위한 기초 사항 설정
- application-modules/api-server
- domain-modules/image-domain
- 위 2가지 모듈을 참고할 수 있도록 예시로 테스트 환경을 구현함.
- build.gradle 의존성 추가 (test h2 db)
close #27
> ✨ Feature: 각 모듈 별 테스트 기본 구조 설정

- .github/workflows/BE-CI.yml
내용을 적어주세요.
be-dev 브랜치 대상 PR CI 작업 수행 설정
- be-dev 브랜치를 베이스로 열린 PR에 대해서 CI 작업을 수행하는 workflow 파일을 작성함.
- java 17, gradle을 기반으로  build, test를 수행함.
- 추후 PR open 시 빌드, 테스트 과정을 거침.
close #19
> ✨ Feature: Backend CI workflow 동작 파일 추가

- backend/common-modules/exception/src/main/java/com/softeer/error/CustomException.java
- backend/common-modules/exception/src/main/java/com/softeer/error/ExceptionInterface.java
- backend/common-modules/exception/src/main/java/com/softeer/error/HttpStatus.java
프로젝트 전반적으로 사용할 HttpStatus 생성
- 기본적으로 사용할 200, 400, 401, 500 HttpStatus 정의
- CustomException status int -> HttpStatus로 타입 변경
- ExceptionInterface status int -> HttpStatus로 타입 변경
close #
> [BE] - ✨ Feature: HttpStatus 정의

- frontend/src/theme/theme.ts
- titleMedium 같이 묶여있던 fontWeight, fontSize를 분해해서 둠
> [FE] - :art: titleMedium 같이 묶여있던 fontWeight, fontSize를 분해해서 둠

- backend/domain-modules/mountain-domain/src/main/java/com/softeer/domain/Course.java
- backend/domain-modules/mountain-domain/src/main/java/com/softeer/mapper/CourseMapper.java
- backend/domain-modules/mountain-domain/src/main/java/com/softeer/repository/impl/CoursePlanJdbcRepository.java
- backend/domain-modules/mountain-domain/src/test/java/com/softeer/repository/impl/CoursePlanJdbcRepositoryIntegrationTest.java
- backend/domain-modules/mountain-domain/src/test/java/com/softeer/repository/impl/CoursePlanJdbcRepositoryTest.java
- backend/domain-modules/mountain-domain/src/test/resources/sql/course-plan-data.sql
- backend/domain-modules/mountain-domain/src/test/resources/sql/course-plan-schema.sql
- backend/domain-modules/mountain-domain/src/testFixtures/java/com/softeer/domain/CourseFixture.java
내용을 적어주세요.
Course 도메인 레코드 필드를 추가함
필드 추가에 따른 테스트 코드를 수정함
- Course.imageUrl 필드 추가
- 필드 추가에 따른 jdbcTemplate 로직 수정
- 테스트 코드 수정
- 테스트 코드 어노테이션 수정
- 통합 테스트의 어노테이션을 수정함
- JdbcTest -> SpringBootTest
- Spring에서 제공하는 Context 캐싱을 이용하기 위함
close #71
> [BE] - ✨ Feature, Test: 

- .github/workflows/FE-CI-CD.yml
- frontend/src/components/molecules/WeatherIndex/WeatherIndex.tsx
프론트엔드의 CI / CD를 구축했습니다
- GitHub의 Action, AWS S3, CloudFront, Route53을 이용해서 main, dev, fe-dev에 push가 일어나면 자동으로 빌드 및 배포를 하도록 구현했습니다.
- https://climbingtoday.site 가 배포된 사이트입니다.
> [FE] - ✨ Feature: 프론트 CI / CD 구축

- backend/domain-modules/build.gradle
- backend/domain-modules/forecast-domain/src/main/java/com/softeer/exception/ForecastException.java
- backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/ForecastAdapter.java
- backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/impl/ForecastQuerydslRepository.java
- backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/impl/ForestAdapterImpl.java
- backend/domain-modules/forecast-domain/src/main/java/com/softeer/service/ForecastUseCase.java
- backend/domain-modules/forecast-domain/src/main/java/com/softeer/service/impl/ForecastUseCaseImpl.java
- backend/domain-modules/forecast-domain/src/test/java/com/softeer/repository/impl/ForecastQuerydslRepositoryTest.java
- backend/domain-modules/forecast-domain/src/test/java/com/softeer/service/ForecastUseCaseTest.java
예보 도메인 관련 비즈니스 로직 구현 및 테스트 코드 작성
- 예보 단건 조회 쿼리 작성
- 주어진 예보 시작 시점을 기준으로 이후 3일 간격의 날씨 예보를 반환하는 로직 작성
- 코스 시간에 따른 각각의 날씨 예보 반환 로직 작성
- 주어진 예보 시작 시점을 기준으로 이후 3일 간격의 날씨 예보를 반환하도록 쿼리 수정
> [BE] - ✨ Feature: 예보 도메인 비즈니스 로직 구현

- backend/domain-modules/image-domain/src/main/java/com/softeer/domain/Image.java
- backend/domain-modules/image-domain/src/main/java/com/softeer/entity/ImageEntity.java
- backend/domain-modules/image-domain/src/main/java/com/softeer/repository/ImageJpaRepository.java
- backend/domain-modules/image-domain/src/testFixtures/java/com/softeer/domain/ImageFixture.java
- backend/domain-modules/user-domain/build.gradle
- backend/domain-modules/user-domain/src/main/java/com/softeer/domain/User.java
- backend/domain-modules/user-domain/src/main/java/com/softeer/entity/Role.java
- backend/domain-modules/user-domain/src/main/java/com/softeer/entity/UserEntity.java
- backend/domain-modules/user-domain/src/main/java/com/softeer/repository/UserJpaRepository.java
- backend/domain-modules/user-domain/src/testFixtures/java/com/softeer/domain/UserFixture.java
유저 jpaEntity와 도메인을 추가했습니다.
- Jpa 엔티티 작성
- 유저 도메인 객체 작성
- ImageFixture 추가
- Image Domain 및 DomainFixture 추가
close #
> [BE] - ✨ Feature: 유저 도메인 JpaEntity 및 도메인 객체 생성

- backend/common-modules/util/src/main/java/com/softeer/apparent/ApparentTemperatureCalculator.java
- backend/common-modules/util/src/main/java/com/softeer/time/ApiTimeUtil.java
- backend/common-modules/util/src/main/java/com/softeer/time/TimeUtil.java
- backend/common-modules/util/src/test/java/com/softeer/time/ApiTimeUtilTest.java
기온, 상대습도, 풍속에 따른 체감 기온을 계산하는 유틸 클래스 구현했습니다.
- 겨울철 체감 기온 로직 구현
- 여름철 체감 기온 로직 구현
- ApiTimeUtil의 불필요한 getMountainBaseTime 메소드 제거
close #
> [BE] - ✨ Feature: 체감 기온 계산 유틸 클래스 구현

- backend/application-modules/api-server/build.gradle
- backend/application-modules/api-server/src/main/java/com/softeer/dto/response/HourlyWeatherResponse.java
- backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/CourseCardResponse.java
- backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/ForecastCardDetail.java
- backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/ForecastCardResponse.java
- backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/MountainCardResponse.java
- backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/WeatherMetric.java
- backend/application-modules/api-server/src/main/java/com/softeer/exception/ExceptionControllerAdvice.java
- backend/application-modules/api-server/src/main/java/com/softeer/exception/ExceptionResponse.java
- backend/application-modules/api-server/src/main/java/com/softeer/presentation/WeatherCardApi.java
- backend/application-modules/api-server/src/main/java/com/softeer/presentation/impl/WeatherCardController.java
- backend/application-modules/api-server/src/main/java/com/softeer/service/WeatherCardService.java
- backend/application-modules/api-server/src/test/java/com/softeer/service/WeatherCardServiceTest.java
- backend/application-modules/build.gradle
- backend/application-modules/setting.gradle
- backend/domain-modules/forecast-domain/src/main/java/com/softeer/domain/Forecast.java
- backend/domain-modules/forecast-domain/src/main/java/com/softeer/domain/condition/TemperatureCondition.java
- backend/domain-modules/forecast-domain/src/main/java/com/softeer/service/ForecastUseCase.java
- backend/domain-modules/forecast-domain/src/main/java/com/softeer/service/impl/ForecastUseCaseImpl.java
- backend/domain-modules/forecast-domain/src/test/java/com/softeer/domain/condition/TemperatureConditionTest.java
- backend/domain-modules/forecast-domain/src/test/java/com/softeer/service/ForecastUseCaseTest.java
- backend/domain-modules/forecast-domain/src/testFixtures/java/com/softeer/domain/ForecastFixture.java
- backend/domain-modules/mountain-domain/src/testFixtures/java/com/softeer/domain/CoursePlanFixture.java
- backend/domain-modules/mountain-domain/src/testFixtures/java/com/softeer/domain/SunTimeFixture.java
날씨, 산 카드와 같은 카드 조회 API를 구현했고 각 API마다 description을 상세하게 적었습니다.
- 산 카드 조회 API 구현
- 날씨 카드 조회 API 구현
- 예보 카드 조회 API 구현
- 요청 시간을 기준으로 예보 조회하는 API 구현
- 예외 처리 로직 기본 세팅
- Swagger 설정 추가
- ForecastUseCase에서 시간 계산을 하는 것이 아닌 WeatherCardService에서 변환 후 파라미터로 전달
> [BE] - ✨ Feature: 카드 관련 API 

- frontend/src/components/molecules/ImageInputField/ImageInputField.tsx
- frontend/src/components/molecules/ModalButton/ModalButton.tsx
- frontend/src/components/molecules/ModalContent/ReportModalContent.tsx
- frontend/src/components/molecules/ModalFooter/ModalFooter.tsx
- frontend/src/components/molecules/ModalHeader/ModalHeader.tsx
- frontend/src/components/molecules/ModalTextInputBox/ModalTextInputBox.tsx
- frontend/src/components/organisms/Modal/BaseModal.tsx
- frontend/src/components/organisms/Modal/ReportModal.tsx
제보하기 모달 UI를 구현했습니다.
- 모달의 이미지 입력필드 구현
- 모달의 텍스트 인풋 구현
- 모달의 라벨 선택 부분 구현
- BaseModal을 범용적으로 사용하기 위해 width를 변경할 수 있도록 수정
- 모달헤더도 너비를 동적으로 적용
> [FE] - ✨ Feature: 제보하기 모달 UI 구현

- backend/application-modules/api-server/build.gradle
- backend/application-modules/api-server/src/main/java/com/softeer/dto/request/SignInRequest.java
- backend/application-modules/api-server/src/main/java/com/softeer/dto/request/SignUpRequest.java
- backend/application-modules/api-server/src/main/java/com/softeer/presentation/SignApi.java
- backend/application-modules/api-server/src/main/java/com/softeer/presentation/impl/SignController.java
- backend/application-modules/api-server/src/main/java/com/softeer/security/JwtException.java
- backend/application-modules/api-server/src/main/java/com/softeer/security/LoginUserId.java
- backend/application-modules/api-server/src/main/java/com/softeer/security/LoginUserIdArgumentResolver.java
- backend/application-modules/api-server/src/main/java/com/softeer/security/auth/JwtGenerator.java
- backend/application-modules/api-server/src/main/java/com/softeer/security/auth/JwtProperties.java
- backend/application-modules/api-server/src/main/java/com/softeer/security/auth/JwtResolver.java
- backend/application-modules/api-server/src/main/java/com/softeer/security/auth/Token.java
- backend/application-modules/api-server/src/main/java/com/softeer/service/SignService.java
- backend/application-modules/api-server/src/main/resources/application.yml
- backend/application-modules/api-server/src/test/java/com/softeer/service/auth/JwtTest.java
- backend/common-modules/exception/src/main/java/com/softeer/error/HttpStatus.java
- backend/domain-modules/user-domain/src/main/java/com/softeer/entity/UserEntity.java
- backend/domain-modules/user-domain/src/main/java/com/softeer/exception/UserException.java
- backend/domain-modules/user-domain/src/main/java/com/softeer/repository/UserAdapter.java
- backend/domain-modules/user-domain/src/main/java/com/softeer/repository/impl/UserAdapterImpl.java
- backend/domain-modules/user-domain/src/main/java/com/softeer/repository/impl/UserJpaRepository.java
- backend/domain-modules/user-domain/src/main/java/com/softeer/service/SignUseCase.java
- backend/domain-modules/user-domain/src/main/java/com/softeer/service/check/LoginIdChecker.java
- backend/domain-modules/user-domain/src/main/java/com/softeer/service/check/PasswordChecker.java
- backend/domain-modules/user-domain/src/main/java/com/softeer/service/impl/SignUseCaseImpl.java
- backend/domain-modules/user-domain/src/test/java/com/softeer/repository/impl/UserJpaRepositoryTest.java
User 도메인의 SignUseCase를 활용해서 회원가입 및 로그인에 필요한 API를 구현
- JwtToken generate 로직 구현
- JwtToken resolve 로직 구현
- 회원 가입 시 필요한 API 구현
- 로그인 시 필요한 API 구현
- 토큰을 검증할 체크할 ArgumentResolver 구현
- 유저 UseCase에서 사용하는 Record 클래스명 Request -> Command로 변경
- 유저 UseCase에서 회원가입 시 유니크 유효성 검사 체크 로직 추가
- 유저 UseCase에서 로그인 시 User 반환하도록 변경
> [BE] - ✨ Feature: 회원가입 및 로그인 API 구현

- backend/application-modules/api-server/src/main/resources/application-prod.yml
CD를 위해 yml 파일 세팅
- jwt.access-token-expiration-ms 세팅
- jwt.secret-key
> [BE] - ⚙️ Setting: application-prod.yml 파일 jwt secretKey 값 세팅

- frontend/src/components/templates/ForecastMain.tsx
- frontend/src/components/templates/Login/MyPageTemplate.tsx
- frontend/src/pages/ForecastPage/ForecastPage.tsx
- frontend/src/pages/LoginPage/MyPage.tsx
배포상태 및 작업 사항을 확인하기 위하여 작업하던 내용들을 모두 push 한 후 확인
- ForecastPage 구현된 컴포넌트 조립
- MyPage 작업중이던 내용 push
> [FE] - ✨ Feature : 배포 상태 확인을 위해 작업 내역 공유

- backend/application-modules/api-server/src/main/java/com/softeer/dto/response/CourseInfoResponse.java
- backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/MountainCardResponse.java
- backend/application-modules/api-server/src/main/java/com/softeer/presentation/WeatherCardApi.java
- backend/application-modules/api-server/src/main/java/com/softeer/presentation/impl/WeatherCardController.java
- backend/application-modules/api-server/src/main/java/com/softeer/service/WeatherCardService.java
- backend/application-modules/api-server/src/test/java/com/softeer/service/WeatherCardServiceTest.java
산 및 코스 정보 조회 API 구현
- MountainCardResponse에 mountainId 추가
- 코스 정보 조회 API 구현
- MountainCardResponse에 mountainId long type 필드 추가
- mountains -> mountain 으로 요청 url 변경
close #
> [BE] - ✨ Feature: 산 및 코스 정보 조회 API 구현

- backend/application-modules/batch-server/src/main/resources/application-prod.yml
> [BE] - 🚀 Release: Batch redis 설정 수정

- backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/CourseScheduleCardResponse.java
- backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/ForecastOverview.java
- backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/MountainCourseCardResponse.java
- backend/application-modules/api-server/src/main/java/com/softeer/presentation/InteractionCommandCardApi.java
- backend/application-modules/api-server/src/main/java/com/softeer/presentation/WeatherCardApi.java
- backend/application-modules/api-server/src/main/java/com/softeer/presentation/impl/WeatherCardController.java
- backend/application-modules/api-server/src/main/java/com/softeer/service/InteractionCommandCardService.java
- backend/application-modules/api-server/src/main/java/com/softeer/service/WeatherCardService.java
- backend/application-modules/api-server/src/test/java/com/softeer/service/WeatherCardServiceTest.java
- backend/common-modules/util/src/main/java/com/softeer/activity/HikingActivityCalculator.java
- backend/domain-modules/interaction-domain/src/main/java/com/softeer/entity/CardHistoryEntity.java
- backend/domain-modules/interaction-domain/src/main/java/com/softeer/repository/history/CardHistoryAdapter.java
- backend/domain-modules/interaction-domain/src/main/java/com/softeer/repository/history/impl/CardHistoryAdapterImpl.java
- backend/domain-modules/interaction-domain/src/main/java/com/softeer/repository/history/impl/CardHistoryJpaRepository.java
- backend/domain-modules/interaction-domain/src/main/java/com/softeer/service/CardHistoryUseCase.java
- backend/domain-modules/interaction-domain/src/main/java/com/softeer/service/impl/CardHistoryUseCaseImpl.java
등산 일정 카드의 뒷면 데이터를 제공하는 api를 구현함.
등산 일정 카드 데이터를 응답하는 시점에 카드 기록 저장 로직을 호출하도록 구현함.
- 등산 일정 카드 뒷면 데이터 응답 제공 api 및 로직 구현
- 카드 기록 저장 로직 구현.
- 등산 일정 생성 api 호출 시 카드 기록 저장 로직 호출 처리
- CardHistoryEntity 오타 및 컬럼명 수정
- Api 명세 오타 수정 (InteractionCommandCardApi)
close #190
> [BE] - ✨ Feature: 카드 기록 저장 로직 구현

- backend/application-modules/batch-server/build.gradle
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/common/config/ForecastApiCallerConfig.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/common/config/WebClientConfig.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/config/ShortForecastJobConfig.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/processor/ShortForecastProcessor.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/ultra/v1/UltraForecastV1JobConfig.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/ultra/v1/UltraForecastV1Processor.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/ultra/v2/UltraForecastV2JobConfig.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/ultra/v2/UltraForecastV2Processor.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/ultra/v2/UltraForecastV2Writer.java
- backend/infrastructure-modules/kma-adapter-module/build.gradle
- backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/common/AbstractKmaApiCaller.java
- backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/mountain/MountainForecastApiCaller.java
- backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/mountain/dto/MountainForecastApiRequest.java
- backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/shortterm/AbstractShortForecastApiCaller.java
- backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/shortterm/ShortForecastApiCaller.java
- backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/shortterm/UltraForecastApiCaller.java
- backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/shortterm/dto/request/ShortForecastApiRequest.java
- backend/infrastructure-modules/kma-adapter-module/src/test/java/com/softeer/mountain/MountainForecastApiCallerTest.java
- backend/infrastructure-modules/kma-adapter-module/src/test/java/com/softeer/shortterm/dto/request/ShortForecastApiRequestTest.java
- backend/infrastructure-modules/redis-module/src/main/java/com/softeer/throttle/ex/ThrottleException.java
- backend/infrastructure-modules/redis-module/src/main/java/com/softeer/throttle/ex/ThrottleExceptionStatus.java
- backend/infrastructure-modules/redis-module/src/main/java/com/softeer/throttle/manager/AsyncRetryHandler.java
- backend/infrastructure-modules/redis-module/src/main/java/com/softeer/throttle/manager/SimpleRetryHandler.java
- backend/infrastructure-modules/redis-module/src/main/java/com/softeer/throttle/manager/ThrottlingManager.java
- backend/infrastructure-modules/redis-module/src/main/java/com/softeer/throttle/task/RetryTask.java
- backend/infrastructure-modules/redis-module/src/main/java/com/softeer/throttle/task/RetryTaskWithBucket.java
- backend/infrastructure-modules/redis-module/src/test/java/com/softeer/throttle/ThrottlingManagerRetryTest.java
- backend/infrastructure-modules/redis-module/src/test/java/com/softeer/throttle/ThrottlingManagerTest.java
비동기로 요청을 보내는 초단기 배치 서버 Version 2 구현
- 동기 요청 Retry handler 구현
- 비동기 요청 Retry handler 구현
- 초단기 배치 서버 Version 2 구현
- 기존 동기 요청시 재시도 가능한 예외 발생했을 때 retry하는 로직 추가
close #
> [BE] - ✨ Feature: 초단기 배치 서버 Version 2 구현

- backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/enums/PrecipitationType.java
- backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/enums/Sky.java
날씨 응답 description 데이터를 변경함.
- PrecipitationType 열거형 displayDescription 수정
- Sky 열거형 displayDescription 수정
- PrecipitationType
- 기존: 빗방울눈날림
- 변경: 진눈깨비
- Sky
- 기존: 맑은 하늘, 조금 흐린 하늘, 흐린 하늘
- 변경: 화창, 구름 많음, 흐림
close #220
> [BE] - 💎 Refactor: 날씨 응답 description 데이터 변경

- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/ultra/v1/UltraForecastV1Writer.java
- backend/domain-modules/interaction-domain/src/main/java/com/softeer/repository/report/impl/ReportQuerydslRepository.java
- backend/domain-modules/interaction-domain/src/main/java/com/softeer/service/impl/ReportCommandUseCaseImpl.java
- backend/scripts/deploy/start_application.sh
제보 좋아요 api 호출 시 매개변수 전달 오류를 해결함.
- 제보 좋아요 api를 호출할 때 userId, reportId를 바꿔 전달하는 오류를 해결함.
- Redis 저장 로직을 실행하는 메서드 호출 주석 처리를 취소함.
close #223
> [BE] - 🐞 BugFix: 코스아이디 유저아이디 순서 조정

- frontend/src/components/molecules/ReportCard/BackReportCardHeader.tsx
- frontend/src/components/molecules/ReportCard/FrontCardFooter.tsx
- frontend/src/components/organisms/Main/MountainCard.tsx
- frontend/src/components/organisms/Report/BackReportCard.tsx
- frontend/src/components/organisms/Report/BaseModal.tsx
- frontend/src/components/organisms/Report/FrontReportCard.tsx
- frontend/src/components/organisms/Report/HeartStat.tsx
- frontend/src/components/templates/Main/MountainCardSection.tsx
- frontend/src/components/templates/Report/ReportCardSection.tsx
- frontend/src/hooks/useApiInfiniteQuery.ts
- frontend/src/pages/MainPage/MainPage.tsx
- frontend/src/pages/ReportPage/ReportPage.tsx
https://github.com/user-attachments/assets/96d734c8-6ed4-40aa-9c5e-81457bbc8e10
https://github.com/user-attachments/assets/b41e8081-d108-4dd7-a0ac-760e723aa418
제보페이지에서의 제보카드들의 무한 스크롤 구현 및 좋아요 낙관적 업데이트를 구현했습니다.
- 무한스크롤을 위한 useInfiniteQuery 훅 구현
- 제보카드 무한스크롤 구현 및 좋아요 낙관적 업데이트 구현
- 제보카드 이미지 주소 추가
- 제보하기 모달이 서치바 뒤로 가는 오류 해결을 위해 z-index 수정
- 좋아요 버튼의 클릭 이벤트에 이벤트 버블링 block
close #231
> [FE] - ✨ Feature: 제보페이지에서의 제보카드들의 무한 스크롤 구현 및 좋아요 낙관적 업데이트 

- .github/workflows/BE-CD.yml
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/common/dto/RedisTtlWrite.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/common/writersupporter/DailyTemperatureWriter.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/common/writersupporter/ForecastJdbcWriter.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/common/writersupporter/SunTimeJdbcWriter.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/chained/context/DailyTemperatureContextAccessor.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/chained/context/ExecutionContextKeys.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/chained/dto/DailyTemperatureKey.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/chained/dto/DailyTemperatureValue.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/config/MountainForecastStepConfig.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/listener/DailyTemperatureLoader.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/redis/MountainForecastRedisWriter.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/writer/AbstractMountainForecastWriter.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/writer/ScheduledMountainForecastWriter.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/writer/StartUpMountainForecastWriter.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/config/ShortForecastStepConfig.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/listener/DailyTemperatureCollector.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/processor/ShortForecastProcessor.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/redis/ShortForecastRedisWriter.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/writer/AbstractShortForecastWriter.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/writer/ScheduledShortForecastWriter.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/writer/StartUpShortForecastWriter.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/ultra/AbstractUltraForecastProcessor.java
- backend/application-modules/batch-server/src/main/resources/application-prod.yml
- backend/common-modules/util/src/main/java/com/softeer/time/TimeUtil.java
- backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/ForecastRedisEntity.java
- backend/infrastructure-modules/redis-module/src/main/java/com/softeer/mapper/RecordMapper.java
산악, 단기 예보 api 응답 데이터 Redis 저장 로직을 구현함.
- 산악, 단기 예보의 응답 데이터를 ForecastRedisEntity 형식으로 Redis에 저장하는 로직을 구현함.
- 단기 예보의 일 최고, 최저 기온을 산악 예보 데이터와 함께 사용할 수 있도록 하기 위해서 ExecutionContext를 사용함.
- ForecastRedisEntity 레코드의 생성자를 추가함.
- Forecast, gridId로 생성
- Forecast, highest, lowest, gridId로 생성
close #227
> [BE] - ✨ Feature: 산악, 단기 예보 api 응답 데이터 Redis 저장

- backend/application-modules/api-server/src/main/resources/application-prod.yml
OSIV 설정 True로 재설정
LazyLoading으로 인한 Proxy Error 수정을 위해 OSIV : True로 설정
close #
> 🚀 Release: OSIV : True로 설정 후 재배포

- frontend/src/components/templates/MyPage/MyLikeSection.tsx
- frontend/src/components/templates/Report/ReportCardSection.tsx
MyLikeSection의 쿼리 키 수정 및 ReportCardSection의 필터 필드명 수정을 진행했습니다
- MyLikeSection의 쿼리 키 수정
- ReportCardSection의 필터 필드명 수정
close #250
> [FE] - 🐞 BugFix: MyLikeSection의 쿼리 키 수정 및 ReportCardSection의 필터 필드명 수정

- backend/application-modules/api-server/src/main/java/com/softeer/config/WebConfiguration.java
CORS 에러를 해결하기 위한 수정 사항 PR
- 사용자 정보 변경을 위한 PATCH 요청 전송 시 CORS 에러 발생 문제를 해결함.
- 허용 method 추가 (HEAD, OPTION, PATCH)
close #252
> [BE] - 🐞 BugFix: 

- backend/application-modules/api-server/src/main/java/com/softeer/config/WebConfiguration.java
CORS 허용 도메인 추가 반영 PR
- CORS 허용 도메인을 추가함
- WebConfiguration 클래스 허용 origin 리스트 추가
> [BE] - ✨ Feature: CORS 허용 도메인 추가

- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/ultra/UltraForecastJobScheduler.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/ultra/v3/UltraForecastV3JobConfig.java
- backend/domain-modules/interaction-domain/src/main/java/com/softeer/repository/history/impl/CardHistoryAdapterImpl.java
- backend/domain-modules/interaction-domain/src/main/java/com/softeer/repository/history/impl/CardHistoryJpaRepository.java
…메서드 수정 (검색 조건에 LocalDateTime 추가)
CardHistory 조회 로직의 검색 조건 누락 문제 해결
- CardHistoryJpaRepository.findByUserIdAndCourseIdAndForecastDate() 메서드의 검색 조건 누락 해결
- LocalDateTime forecastDate 조건을 추가함
close #262
> [BE] - 🐞 BugFix: CardHistory 조회 로직의 검색 조건 누락 문제 해결

- frontend/src/components/organisms/Loading/Loading.tsx
예보페이지의 로딩창에서 스크롤이 되는 오류를 수정했습니다
- useEffect를 통해 마운트 시 body의 overscroll속성을 hidden, 마운트 해제 시 설정한 속성을 지웁니다.
close #271
> [FE] - 🐞 BugFix: 예보페이지 로딩창 스크롤 버그 수정

- frontend/src/components/templates/Forecast/DetailInfoSection.tsx
weekdayid 쿼리 파라미터 값을 ScrollSelectedTime 상태에 반영될 수 있도록 변경 
- useEffect를 통하여 쿼리 파라미터가 변하면 이를 감지하여 상태변화
- useEffect를 통하여 쿼리 파라미터가 변하면 이를 감지하여 상태변화
close #275
> [FE] - 🐞 BugFix: selectedWeekdayId변화를 ScrollSelectedTime에 반영

- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/redis/MountainForecastRedisWriter.java
- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/redis/ShortForecastRedisWriter.java
Batch-server의 redis writer에서 데이터를 저장할 때 3일 뒤의 데이터를 저장하지 않도록 수정함.
- redis writer에 전달된 chunk의 LocalDate를 기준으로 필터링 수행
- redis writer에서 stream으로 redis에 저장할 Map 형식의 데이터를 생성하는 과정에 chunk의 날짜를 기준으로 필터링 로직을 추가함.
close #277
> [BE] - ✨ Feature: 

- backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/ultra/redis/UltraForecastRedisEntity.java
데이터를 Redis에 저장하는 과정에 필터링(3일 이후의 데이터 삭제) 과정을 추가한 사항을 반영하는 배포 PR입니다.
- ShortRedisWriter, MountainRedisWriter의 chunk 필터링 로직을 추가함.
- 기존: redis writer에 전달 받은 모든 chunk를 redis에 저장함.
- 변경: redis writer에서 전달 받은 chunk를 필터링 후 redis에 저장함.
> [BE] - 🚀 Release: Redis 데이터 저장 필터링 추가 배포

- frontend/src/components/templates/Alert/AlertSearchSection.tsx
- frontend/src/components/templates/Forecast/ForecastSearchSection.tsx
- frontend/src/components/templates/Main/hooks/useMainSearchSection.ts
- frontend/src/components/templates/Main/hooks/useMountainCardSection.ts
- frontend/src/components/templates/MyPage/MyLikeSection.tsx
- frontend/src/components/templates/MyPage/MyReportSection.tsx
- frontend/src/components/templates/Report/ReportSearchSection.tsx
- frontend/src/components/templates/Report/hooks/useReportCardSection.ts
- frontend/src/components/templates/Report/hooks/useReportSearchSection.ts
- frontend/src/constants/placeholderData.ts
메인페이지와 제보페이지의 gcTime 및 placeholderData를 수정했습니다
- 제보하기 및 메인페이지의 gcTime 설정
- 제보카드들 placeholder설정
- 필터 placeholderData설정 및 하드코딩 된 필더 데이터 삭제
close #301
> [FE] - 💎 Refactor: gcTime 및 placeholderData 수정
